- name: Load relevant secrets
  include_vars: "~/0/vault/proxmox.yml"
  no_log: false


- name: 'create vms'
  proxmox_kvm:
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    vmid: '{{ hostvars[item].vmid }}'
    node: '{{ hostvars[item].proxmox_node }}'
    name: '{{ hostvars[item].inventory_hostname }}'
    cores: '{{ hostvars[item].cores | default(defaults.cores) }}'
    net: "{{ '{\"net0\":\"virtio=' + hostvars[item].mac_address + ',bridge=vmbr0\"}' | default(defaults.netif) }}"
    virtio: '{{ hostvars[item].virtio | default(defaults.virtio) }}'
    vga: 'qxl'
    memory: '{{ hostvars[item].memory | default(defaults.memory.vm) }}'
    storage: '{{ hostvars[item].storage | default(defaults.storage.gluster) }}'
    onboot: '{{ hostvars[item].onboot | default(defaults.onboot) }}'
    #args: '-device virtio-rng-pci,id=rng0,bus=pci.0,addr=0x17'
    state: 'present'
  when: hostvars[item].mac_address is defined
  with_items: "{{ deploy_vms }}"
  loop_control:
    pause: 5
  notify:
    - 'sleep'
  register: 'created_vms_pve'


- meta: 'flush_handlers'
  when: 'created_vms_pve.changed'

- name: 'start VMs'
  proxmox_kvm:
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    node: "{{ item['invocation']['module_args']['node'] }}"
    name: "{{ item['item'] }}"
    state: 'started'
  with_items: "{{ created_vms_pve.results }}"
  notify:
    - 'sleep'
  #when: 'item.changed'


- meta: 'flush_handlers'
  when: 'created_vms_pve.changed'
