---
  - name: Include secrets
    include_vars: ~/0/vault/secrets.yml

  - name: Generate unattended install
    template:
      src: templates/kickstart.j2
      dest: "{{ ks_dir }}/{{ hostvars[item].inventory_hostname_short }}.ks"
    with_items: "{{ groups['all'] | difference(groups['proxmox']) }}"

  - name: generate pxe files
    template:
      src: templates/pxe.j2
      dest: "{{ menu_dir }}/01-{{ hostvars[item]['mac_address']|regex_replace(':','-')|lower }}"
    with_items: "{{ groups['all'] }}"
    when: hostvars[item]['mac_address'] is defined
