---
# - name: Prepare storage
#   hosts: bronze.lan.nathancurry.com
#   gather_facts: true
#   become: true
#
#   roles:
#     - preparestorage

# Allow container to reboot if necessary.
  # tasks:
  # - name: sleep
  #   pause:
  #     seconds: 15

- name: Configure local repo server
  hosts: repo.lan.nathancurry.com
  gather_facts: true
  become: true

  roles:
    # - chronyclient
    - kickstart
    - reposerver
    - tftpserver
