---
- name: configure repo host
  hosts: 'repo.lan.nathancurry.com'

  vars:
    packages: [ 'httpd', 'createrepo', 'yum-utils']

  tasks:
  - name: Link /var/www/ to data
    file:
      src: /data/www
      dest: /var/www
      owner: root
      group: root
      state: link

  - name: Install packages
    yum:
      name: '{{ packages }}'
      state: 'present'
      update_cache: 'yes'

  - name: Turn on web server
    service:
      name: httpd
      state: started

  - name: make repo directory
    file:
      dest: '/data/www/html/repo/centos7'
      state: 'directory'
      owner: 'root'
      group: 'apache'
      mode: '0750'

  - name: make metadata dir
    file:
      dest: '/data/www/html/repo/meta'
      state: 'directory'
      owner: 'root'
      group: 'apache'
      mode: '0750'

  - name: install centos7.repo
    copy:
      src: '../files/centos7.repo'
      dest: '/data/www/html/repo/meta/centos7.repo'
      owner: 'root'
      group: 'root'
      mode: '0600'

  - name: Set reposync cron file
    cron:
      name: 'reposync centos7'
      weekday: '*'
      minute: 0
      hour: 1
      user: root
      job: "reposync -n -d -a x86_64 -p /data/www/html/repo/centos7 -c /data/www/html/repo/meta/centos7.repo"
      cron_file: 'ansible_reposync-centos7'

  - name: Make local repo available on server
    copy:
      src: '../files/local.repo'
      dest: '/data/www/html/repo/centos7-local.repo'
      owner: 'root'
      group: 'root'
      mode: '0644'
