---
- name: Prepare host node
  hosts: bronze.lan.nathancurry.com

  vars:
    vmid: 203

  tasks:
    - name:  Make sure mount directory exists
      file:
        state: 'directory'
        path: /mnt/external
        owner: root
        group: root
        mode: 0755

    - name: Mount up device by UUID
      mount:
        path: /mnt/external
        src: UUID=22d8ad98-9571-40ef-b816-9e05f7e20152
        fstype: ext4
        opts: relatime
        state: mounted

    - name: Load secrets
      include_vars: "~/0/vault/proxmox.yml"
      no_log: true

    - name: Add bind Mount
      command: "pct set {{ vmid }} -mp0 /mnt/external,mp=/data"
      nofity: restart container

    - name: restart container
      proxmox:
        api_host: 'bronze'
        api_user: 'root@pam'
        api_password: '{{api_password}}'
        vmid: '{{ vmid }}'
        state: restarted
