---
# - hosts: repo.lan.nathancurry.com
#   tasks:
#   - include_tasks: ../roles/tftpserver/tasks/start.yml

- hosts: gold.lan.nathancurry.com
  roles:
  - deployvms
# - hosts: repo.lan.nathancurry.com
#   tasks:
#   - include_tasks: ../roles/tftpserver/tasks/stop.yml
