---
- name: enable SSH user
  hosts: ipareplicas
  # user: root
  become: true

  roles:
    - sshenableuser

- name: disable SSH root
  hosts: ipareplicas
  become: true

  #  tasks:
          #    - name: Install python
          #raw: "yum -y install python2 python3"

  roles:
    - sshdisableroot
    - repoclient
