---
- name: Set up local repositories
  block:
    - yum_repository:
        name: '{{ item }}'
        state: absent
      with_items:
        - base
        - extras
        - updates
        - epel
    - copy:
        src: 'local.repo'
        dest: '/etc/yum.repos.d/local.repo'
        owner: 'root'
        group: 'root'
        mode: '0644'
  when: (ansible_distribution == "CentOS")
