---
- name: Link /var/www/ to data
  file:
    src: /data/www
    dest: /var/www
    owner: root
    group: root
    state: link

- name: Install packages
  yum:
    name: '{{ packages }}'
    state: 'present'
    update_cache: 'yes'

- name: Turn on web server
  service:
    name: httpd
    state: started

- name: make dirs
  file:
    dest: '/data/www/html/{{ item }}'
    state: 'directory'
    owner: 'root'
    group: 'apache'
    mode: '0750'
  with_items:
    - 'repo'
    - 'meta/repos'

- name: Install reposync.conf
  copy:
    src: 'reposync.conf'
    dest: '/data/www/html/meta/reposync.conf'
    owner: 'root'
    group: 'root'
    mode: '0600'

- name: install reposync.repo
  copy:
    src: 'reposync.repo'
    dest: '/data/www/html/meta/repos/reposync.repo'
    owner: 'root'
    group: 'root'
    mode: '0600'

- name: Set reposync cron file
  cron:
    name: 'reposync'
    weekday: '*'
    minute: 0
    hour: 1
    user: root
    job: "reposync -n -d -a x86_64 -p /data/www/html/repo/ -c /data/www/html/meta/reposync.conf"
    cron_file: 'ansible_reposync'

- name: Make local repo available on server
  copy:
    src: '../files/local.repo'
    dest: '/data/www/html/repo/centos7-local.repo'
    owner: 'root'
    group: 'root'
    mode: '0644'
